/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bw.utils;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.JOptionPane;

/**
 *
 * @author byteworks
 */
public class SimpleCalculator extends javax.swing.JFrame {

    String operand;
    double operand1 = 0;
    double operand2 = 0;
    static int operator = 0;
     String result="";


     ResultSet resultSet = null;
     ResultSet timeResultSet = null;
     static Statement statement = null;
      static Statement statementTime = null;
   DataBaseHelper dataBaseHelper = new DataBaseHelper();





    /**
     * Creates new form SimpleCalculator
     */
    public SimpleCalculator() throws SQLException {
        initComponents();
        this.setResizable(false);
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
           dataBaseHelper.connect();
                statement = dataBaseHelper.connection.createStatement();
               statementTime = dataBaseHelper.connection.createStatement();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        calculatorPanel = new javax.swing.JPanel();
        displayOperation = new javax.swing.JTextField();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnClearScreen = new javax.swing.JButton();
        memoryCall = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        divideOperation = new javax.swing.JButton();
        multiplyOperation = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnZeroZero = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnAddOperation = new javax.swing.JButton();
        btnEqualsTo = new javax.swing.JButton();
        btnSubtractOperation = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Calculator");

        calculatorPanel.setBackground(new java.awt.Color(202, 205, 145));

        displayOperation.setEditable(false);
        displayOperation.setBackground(new java.awt.Color(253, 255, 172));
        displayOperation.setFont(new java.awt.Font("Digital-7", 0, 36)); // NOI18N
        displayOperation.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayOperationActionPerformed(evt);
            }
        });

        btnSeven.setBackground(new java.awt.Color(255, 255, 255));
        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnEight.setBackground(new java.awt.Color(255, 255, 255));
        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnNine.setBackground(new java.awt.Color(255, 255, 255));
        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnClearScreen.setBackground(new java.awt.Color(255, 244, 0));
        btnClearScreen.setText("CE");
        btnClearScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearScreenActionPerformed(evt);
            }
        });

        memoryCall.setBackground(new java.awt.Color(255, 244, 0));
        memoryCall.setText("MC");
        memoryCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoryCallActionPerformed(evt);
            }
        });

        btnFour.setBackground(new java.awt.Color(255, 255, 255));
        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setBackground(new java.awt.Color(255, 255, 255));
        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setBackground(new java.awt.Color(255, 255, 255));
        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        divideOperation.setBackground(new java.awt.Color(255, 244, 0));
        divideOperation.setText("/");
        divideOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideOperationActionPerformed(evt);
            }
        });

        multiplyOperation.setBackground(new java.awt.Color(255, 244, 0));
        multiplyOperation.setText("X");
        multiplyOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyOperationActionPerformed(evt);
            }
        });

        btnThree.setBackground(new java.awt.Color(255, 255, 255));
        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnTwo.setBackground(new java.awt.Color(255, 255, 255));
        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnOne.setBackground(new java.awt.Color(255, 255, 255));
        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnZeroZero.setBackground(new java.awt.Color(255, 255, 255));
        btnZeroZero.setText("00");
        btnZeroZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroZeroActionPerformed(evt);
            }
        });

        btnBackspace.setBackground(new java.awt.Color(255, 244, 0));
        btnBackspace.setText("←");
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });

        btnZero.setBackground(new java.awt.Color(255, 255, 255));
        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnAddOperation.setBackground(new java.awt.Color(255, 244, 0));
        btnAddOperation.setText("+");
        btnAddOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOperationActionPerformed(evt);
            }
        });

        btnEqualsTo.setBackground(new java.awt.Color(255, 244, 0));
        btnEqualsTo.setText("=");
        btnEqualsTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsToActionPerformed(evt);
            }
        });

        btnSubtractOperation.setBackground(new java.awt.Color(255, 244, 0));
        btnSubtractOperation.setText("-");
        btnSubtractOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractOperationActionPerformed(evt);
            }
        });

        btnHelp.setBackground(new java.awt.Color(255, 244, 0));
        btnHelp.setText("?");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout calculatorPanelLayout = new javax.swing.GroupLayout(calculatorPanel);
        calculatorPanel.setLayout(calculatorPanelLayout);
        calculatorPanelLayout.setHorizontalGroup(
            calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayOperation)
                    .addGroup(calculatorPanelLayout.createSequentialGroup()
                        .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calculatorPanelLayout.createSequentialGroup()
                                .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnZeroZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(calculatorPanelLayout.createSequentialGroup()
                                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(calculatorPanelLayout.createSequentialGroup()
                                        .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, calculatorPanelLayout.createSequentialGroup()
                                        .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(calculatorPanelLayout.createSequentialGroup()
                                        .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(calculatorPanelLayout.createSequentialGroup()
                                        .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(divideOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(calculatorPanelLayout.createSequentialGroup()
                                        .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(multiplyOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(calculatorPanelLayout.createSequentialGroup()
                                        .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSubtractOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(calculatorPanelLayout.createSequentialGroup()
                                        .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEqualsTo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAddOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(calculatorPanelLayout.createSequentialGroup()
                                .addComponent(btnClearScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memoryCall, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calculatorPanelLayout.setVerticalGroup(
            calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memoryCall, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divideOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplyOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubtractOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calculatorPanelLayout.createSequentialGroup()
                        .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calculatorPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(calculatorPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAddOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(calculatorPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZeroZero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEqualsTo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calculatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calculatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubtractOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractOperationActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "-");
    }//GEN-LAST:event_btnSubtractOperationActionPerformed

    private void btnEqualsToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsToActionPerformed
     operand =  displayOperation.getText();

     if(!"".equals(operand) && operand != null){

         try {
             // TODO add your handling code here:


             ScriptEngineManager manager = new ScriptEngineManager();
             ScriptEngine engine = manager.getEngineByName("JavaScript");

             result = engine.eval(operand).toString();

             if (!result.equals("Infinity")) {
                 displayOperation.setText(result);
                 String sqlStatement = "INSERT INTO operations (result) VALUES ("+result+");";

                 statement.executeUpdate(sqlStatement);

             }else{

                 displayOperation.setText("undefined");
             }

         } catch (SQLException ex) {
             Logger.getLogger(SimpleCalculator.class.getName()).log(Level.SEVERE,null, ex);


         } catch (ScriptException ex) {
             Logger.getLogger(SimpleCalculator.class.getName()).log(Level.SEVERE, null, ex);

             JOptionPane.showMessageDialog(null, "Wrong input!!! \nPlease type operands in the appropiate format");
             displayOperation.setText("");
         }
     }
        else{
         System.out.println("no operation entered");
     }
    }//GEN-LAST:event_btnEqualsToActionPerformed

    private void btnAddOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOperationActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "+");

    }//GEN-LAST:event_btnAddOperationActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "0");

    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackspaceActionPerformed
        // TODO add your handling code here:
//         timeDisplay.setVisible(false);
        String backSpace = displayOperation.getText().toString();

        if (backSpace.equals("")) {
            return;
        }
        else{
            String newDisplayOperation = backSpace.substring(0, (backSpace.length() - 1));
            displayOperation.setText(newDisplayOperation);
        }

    }//GEN-LAST:event_btnBackspaceActionPerformed

    private void btnZeroZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroZeroActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "00");
        operand1 = 100;
    }//GEN-LAST:event_btnZeroZeroActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "1");
        operand1 = 1;
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "2");
        operand1 = 2;
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "3");
        operand1 = 3;
    }//GEN-LAST:event_btnThreeActionPerformed

    private void multiplyOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyOperationActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "*");
    }//GEN-LAST:event_multiplyOperationActionPerformed

    private void divideOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideOperationActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "/");

    }//GEN-LAST:event_divideOperationActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "6");
        operand1 = 6;
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "5");
        operand1 = 5;
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "4");
        operand1 = 4;
    }//GEN-LAST:event_btnFourActionPerformed

    private void memoryCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoryCallActionPerformed
        // TODO add your handling code here: wiil solve the database here
        String resultOutput = "";
        String timeOutput = "";

        String sqlStatement = "SELECT result FROM operations ORDER BY id DESC LIMIT 1;";
        String sqlFetchTime = "SELECT time FROM operations ORDER BY id DESC LIMIT 1;";
        try {

            resultSet = statement.executeQuery(sqlStatement);
            timeResultSet = statementTime.executeQuery(sqlFetchTime);
            while (resultSet.next() && timeResultSet.next()) {

                resultOutput = resultSet.getString("result");
                timeOutput = timeResultSet.getString("time");

            }

           String database24hoursTime =  timeOutput.substring(0,1);
            Integer time24hours = Integer.parseInt(database24hoursTime);
            if (time24hours > 12 ) {
                time24hours -= 12;
            }
            displayOperation.setText(resultOutput);
            // timeDisplay.setText(time24hours.toString() + ""
                //     + timeOutput.substring(2, timeOutput.length()-1));

        } catch (SQLException ex) {
            Logger.getLogger(SimpleCalculator.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_memoryCallActionPerformed

    private void btnClearScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearScreenActionPerformed
        // TODO add your handling code here:
        displayOperation.setText("");
   //     timeDisplay.setVisible(false);
    }//GEN-LAST:event_btnClearScreenActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "9");

    }//GEN-LAST:event_btnNineActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "8");
        operand1 = 8;
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        // TODO add your handling code here:
        displayOperation.setText(displayOperation.getText()+ "7");
        operand1 = 7;

    }//GEN-LAST:event_btnSevenActionPerformed

    private void displayOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayOperationActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_displayOperationActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        
            // JOptionPane.showMessageDialog(null, "Wrong input!!! \nPlease type operands in the appropiate format");
             
             
             JOptionPane.showMessageDialog(rootPane, "SIMPLE CALCULATOR \n"
                     + "A simple calculator that can perform\n"
                     + "basic arithmetic computations with MC (Memory call)\n"
                     + "that retrieves the result of the most recent operation \n\n Developed by Ikechukwu Ezugworie \n"
                     + "Graduate Trainee Byteworks Solutions Ltd.\n"
                     + "www.byteworks.com.ng © 2019");
             displayOperation.setText("");
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>




        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SimpleCalculator().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SimpleCalculator.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOperation;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnClearScreen;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqualsTo;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSubtractOperation;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton btnZeroZero;
    private javax.swing.JPanel calculatorPanel;
    private javax.swing.JTextField displayOperation;
    private javax.swing.JButton divideOperation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton memoryCall;
    private javax.swing.JButton multiplyOperation;
    // End of variables declaration//GEN-END:variables
}
